### ISSUE TITLE
Not getting Clean output to feed it to other tools

### ISSUE THREAD

**Issue by attacker34** [Edu4rdSHL/findomain#100]
Hi ,

I have tried to run the tool and wanna pipe the output to some other tools but could not get the clean output consisting only subdomains.I've used this command

```
findomain -t example.com -r -u example.txt

```

**Comment by sumgr0** [comment]
Hi @attacker34 

The pipe works in the below format (ex. to httprobe)

findomain -t example.com -r | httprobe 
try the same format and report if it does not still work along with the tool you are trying to send the data to.

Cheers!

**Comment by attacker34** [comment]
Great... Its working

**Comment by Edu4rdSHL** [comment]
Also you can use the -q option to avoid informational messages.
