### ISSUE TITLE
The * API has failed returning the following HTTP status: 404 or 403 Not Found

### ISSUE THREAD

**Issue by ahmed1231230** [Edu4rdSHL/findomain#104]
Hello, I am facing a problem and the links are expired or not available 

I tried to modify the code, but the file appears to be encoded in a way that I don't understand, can you help me solve that problem

**Comment by Edu4rdSHL** [comment]
Paste the log of the exact problem you're having and if possible, the domain you're using for testing.

**Comment by ahmed1231230** [comment]
![iasd](https://user-images.githubusercontent.com/52584554/85895786-9c946f00-b7f7-11ea-8034-e3814388671b.png)

**Comment by Edu4rdSHL** [comment]
What's the output for `findomain -V`?

**Comment by ahmed1231230** [comment]
**1.7.0**

**Comment by Edu4rdSHL** [comment]
Thanks, you're using the pre-compiled binaries, right? There's a problem with them that doesn't include the latest commits. You can compile from source or wait a few minutes while I upload the new ones.

**Comment by ahmed1231230** [comment]
Looks like I can't translate from Source, so I will wait until the files are updated
thanks for the help

**Comment by Edu4rdSHL** [comment]
New binaries were uploaded minutes ago, please download again.

**Comment by ahmed1231230** [comment]
### Thank you, the problem was solved
