### ISSUE TITLE
Subdomains starting with *. are not reported

### ISSUE THREAD

**Issue by attacker007** [Edu4rdSHL/findomain#107]
Hi @Edu4rdSHL 

It seems like facebook API Key is not working Properly.. If i manually go to 

````
https://developers.facebook.com/tools/ct/search/?query=

````

and search for a domain... I got more than 10,000 Results... 
but when i used findomain (configured fb access-token) .. I got only 4000 Results (Keeping in mind that Findomain used other API tools too for finding subdomains-)... 

Note: I have not used tag "-r" to check for the only resolved ones... 

 
Can you please check this issue?

Sincerely,

**Comment by Edu4rdSHL** [comment]
How are you configuring it?

**Comment by attacker007** [comment]
I used Command as written in wiki

```
findomain_fb_token="XXXXXXXXXX|XXXXXXXXXXXXXXXXX" ./findomain -t example.com

```

**Comment by Edu4rdSHL** [comment]
Can you give me the domain to reproduce the issue?

**Comment by attacker007** [comment]
Hi @Edu4rdSHL 

You can use "Yahoo.com" as example too. I've not tried using it via config file but why its not working with "findomain_fb_token="XXXXXXXXXX|XXXXXXXXXXXXXXXXX" ./findomain -t example.com
"  ? 
I will try to Update the ticket after testing it with config file(will add token in .bashrc). In the meantime, Can you just copy the tool & test in Ubuntu. 


Sincerely,

**Comment by Edu4rdSHL** [comment]
This should work, can you paste the full output of the command you're running? Is there some error from the Facebook API? I will look into it in some hours.

**Comment by attacker007** [comment]
Hi @Edu4rdSHL  

There is No Error with using in Command line as "findomain_fb_token="XXXXXXXXXX|XXXXXXXXXXXXXXXXX" ./findomain -t example.com" 


But when i added fb token in .bashrc file I got following Error : 

```
The Facebook API has failed returning the following HTTP status: 403 Forbidden

```

**Comment by Edu4rdSHL** [comment]
I have checked and the problem is:

The API that we use for this is `https://graph.facebook.com/certificates?query=yahoo.com&fields=domains&limit=10000&access_token=your_token` which output the same number of subdomains you have seen but a LOT of them are invalid (those who start with `*`), see the next image:

![image](https://user-images.githubusercontent.com/32582878/88195203-5ddeb280-cc05-11ea-8e63-7849d5a1b32e.png)
All those subdomains starting with `*` are automatically excluded by Findomain because they're NXDOMAINs. If the tool doesn't give you any error message means that the subdomains where extracted successfully and there's nothing to worry.

**Comment by attacker007** [comment]
Hi @Edu4rdSHL  I think there is dire need to implement it correctly...  By using limit(100) or (10000) we get same one Page consisting 100 Results... It don't go for other pages at all.  

Its not about the subdomains or domains starting with * ... A lot of other subdomains are being reported.  As the logic work... Tool should report all the subdomains if we don't use ( -r ) .. 


Sincerely,

**Comment by Edu4rdSHL** [comment]
@attacker007 the limit is 5k of subdomains, not 100 and we're iterating over pages as well. See:

![image](https://user-images.githubusercontent.com/32582878/88199035-f9722200-cc09-11ea-9666-aed83a353c2b.png)

And there isn't plans to report subdomains starting with `*` because they are clearly NXDOMAINs. What I can do is check if the subdomain starts with `*.` and remove that characters from the string so that you have only the subdomain part. (This was suggested by @sumgr0)

**Comment by attacker007** [comment]
Hi @Edu4rdSHL  Not talking about subdomains report related to * ... 

Only problem is tool should report all results (Like If i manually crawl for my target , I will get 10,000 results [Dead+Alive] ) but with tool I am not even getting 5,000 subdomains ... 

 
Yes, This is obvious thing. 

```
* because they are clearly NXDOMAINs

```

I manually checked that my target was not having that much subdomains starting with *  


Thanks !!

**Comment by sumgr0** [comment]
Yes, let's at least have the prefix *. removed from the results and add them to the list.

**Comment by sumgr0** [comment]
> Hi @Edu4rdSHL  Not talking about subdomains report related to * ... 
> 
> 
> 
> Only problem is tool should report all results (Like If i manually crawl for my target , I will get 10,000 results [Dead+Alive] ) but with tool I am not even getting 5,000 subdomains ... 
> 
> 
> 
>  
> 
> Yes, This is obvious thing. 
> 
> 
> 
> ```
> 
> * because they are clearly NXDOMAINs
> 
> 
> 
> ```
> 
> 
> 
> I manually checked that my target was not having that much subdomains starting with *  
> 
> 
> 
> 
> 
> Thanks !!
> 
> 

Could you share the exact command you are using for more clarity and testing.

**Comment by Edu4rdSHL** [comment]
> Only problem is tool should report all results (Like If i manually crawl for my target , I will get 10,000 results [Dead+Alive] ) but with tool I am not even getting 5,000 subdomains ...

Please have in mind that there are a lot of duplicates. Are you removing duplicated ones? If there are 10k of subdomains reported by the API but only 10 unique, the tool will report just 10.

**Comment by attacker007** [comment]
> > Hi @Edu4rdSHL  Not talking about subdomains report related to * ...
> > Only problem is tool should report all results (Like If i manually crawl for my target , I will get 10,000 results [Dead+Alive] ) but with tool I am not even getting 5,000 subdomains ...
> > Yes, This is obvious thing.
> > ```
> > 
> > * because they are clearly NXDOMAINs
> > ```
> > 
> > 
> > I manually checked that my target was not having that much subdomains starting with *
> > Thanks !!
> 
> Could you share the exact command you are using for more clarity and testing.

Using this Command:

```
findomain_fb_token="XXXXXXXXXX|XXXXXXXXXXXXXXXXX" ./findomain -t example.com

```

**Comment by attacker007** [comment]
> > Only problem is tool should report all results (Like If i manually crawl for my target , I will get 10,000 results [Dead+Alive] ) but with tool I am not even getting 5,000 subdomains ...
> 
> Please have in mind that there are a lot of duplicates. Are you removing duplicated ones? If there are 10k of subdomains reported by the API but only 10 unique, the tool will report just 10.

Yes, I've checked ... Ratio is not like that ... Mostly are unique subdomain prefixes. its not  like 10k to => 10 or 100 or 5000  unique results..


Regards,

**Comment by attacker007** [comment]
> @attacker007 the limit is 5k of subdomains, not 100 and we're iterating over pages as well. See:
> 
> ![image](https://user-images.githubusercontent.com/32582878/88199035-f9722200-cc09-11ea-9666-aed83a353c2b.png)
> 
> And there isn't plans to report subdomains starting with `*` because they are clearly NXDOMAINs. What I can do is check if the subdomain starts with `*.` and remove that characters from the string so that you have only the subdomain part. (This was suggested by @sumgr0)


That can be the main problem here... the Limit of 5000 Results... That's why tool cant go farther than 5000 results.

**Comment by Edu4rdSHL** [comment]
@attacker007 I have explained that the tool already iterates over pages. Also, I can't reproduce your issue, I have tried the latest release of the tool using the findomain_fb_token variable and I got:
```
A total of 16196 subdomains were found for domain yahoo.com 👽 in 21 seconds.⏲️
>> 📁 Subdomains for yahoo.com were saved in: ./yahoo.com.txt 😀
```
Not 5000 as you said. Adding *. subdomains to scope I got:
```
A total of 17877 subdomains were found for domain yahoo.com 👽 in 28 seconds.⏲️
>> 📁 Subdomains for yahoo.com were saved in: ./yahoo.com.txt 😀
```
That's ~1.7k of more subdomains but in any of the cases I see only 5k of subdomains.

**Comment by attacker007** [comment]
> @attacker007 I have explained that the tool already iterates over pages. Also, I can't reproduce your issue, I have tried the latest release of the tool using the findomain_fb_token variable and I got:
> 
> ```
> A total of 16196 subdomains were found for domain yahoo.com 👽 in 21 seconds.⏲️
> >> 📁 Subdomains for yahoo.com were saved in: ./yahoo.com.txt 😀
> ```
> 
> Not 5000 as you said. Adding *. subdomains to scope I got:
> 
> ```
> A total of 17877 subdomains were found for domain yahoo.com 👽 in 28 seconds.⏲️
> >> 📁 Subdomains for yahoo.com were saved in: ./yahoo.com.txt 😀
> ```
> 
> That's ~1.7k of more subdomains but in any of the cases I see only 5k of subdomains.


Thanks... I thought you were saying that there is a limit of 5K... I misunderstood that...
