### ISSUE TITLE
Use CrtSH DB to prevent timeouts 

### ISSUE THREAD

**Issue by 0xtavian** [Edu4rdSHL/findomain#11]
CRT API will timeout when attempting to return very large results, a solution could be to use the CRT DB like what was done here https://github.com/yassineaboukir/sublert/blob/master/sublert.py#L158
official announcement of the CRT DB was done here https://groups.google.com/d/msg/crtsh/sUmV0mBz8bQ/K-6Vymd_AAAJ

**Comment by Edu4rdSHL** [comment]
Hey @0xtavian, added. Thank you.
