### ISSUE TITLE
About Facebook API

### ISSUE THREAD

**Issue by gaoyang-china** [Edu4rdSHL/findomain#113]
How to set facebook api in findomain(free version)? I can not find the document about facebook api setting.

**Comment by Edu4rdSHL** [comment]
Hello, please see https://github.com/Edu4rdSHL/findomain/blob/master/docs/INSTALLATION.md#configuring-the-facebook-api. You can configure the API key using a configuration file as shown in the [config examples](https://github.com/Edu4rdSHL/findomain/tree/master/config_examples) and pass the file using the `-c` option.
