### ISSUE TITLE
Error while compiling findomain

### ISSUE THREAD

**Issue by sxcurit** [Edu4rdSHL/findomain#116]
```
root@reconpad:~/tools/findomain# cargo -V
cargo 1.46.0 (149022b1d 2020-07-17)                    
```
root@reconpad:~/tools/findomain# cargo build --release        Compiling findomain v2.1.1 (/root/tools/findomain)      error: could not compile findomain.                                                                                 Caused by:process didn't exit successfully: rustc --crate-name findomain --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=z -C lto=fat -C codegen-units=1 -C metadata=41ee7a0d3cd300e2 -C extra-filename=-41ee7a0d3cd300e2 --out-dir /root/tools/findomain/target/release/deps -L dependency=/root/tools/findomain/target/release/deps --extern clap=/root/tools/findomain/target/release/deps/libclap-9976a63bb6d6dfdd.rlib --extern config=/root/tools/findomain/target/release/deps/libconfig-4ee2eff0003b0cf3.rlib --extern failure=/root/tools/findomain/target/release/deps/libfailure-fa01e87317c664bb.rlib --extern findomain=/root/tools/findomain/target/release/deps/libfindomain-a1af50fc4e3d7413.rlib --extern lazy_static=/root/tools/findomain/target/release/deps/liblazy_static-bed4dbbf521977aa.rlib --extern postgres=/root/tools/findomain/target/release/deps/libpostgres-b5663edfcf9dab5c.rlib --extern rand=/root/tools/findomain/target/release/deps/librand-555fbcdfbc120cda.rlib --extern rayon=/root/tools/findomain/target/release/deps/librayon-0afaccbc26ac358a.rlib --extern reqwest=/root/tools/findomain/target/release/deps/libreqwest-c4a3faf357d5f71a.rlib --extern semver=/root/tools/findomain/target/release/deps/libsemver-5533e601ed6eb164.rlib --extern serde=/root/tools/findomain/target/release/deps/libserde-048f0e44383a03af.rlib --extern serde_derive=/root/tools/findomain/target/release/deps/libserde_derive-196c6908b25a61be.so --extern trust_dns_resolver=/root/tools/findomain/target/release/deps/libtrust_dns_resolver-fe0329531197da3f.rlib --extern url=/root/tools/findomain/target/release/deps/liburl-4e283f5073057d03.rlib -L native=/root/tools/findomain/target/release/build/backtrace-sys-290b67c349c2b36c/out -L native=/root/tools/findomain/target/release/build/openssl-sys-3161a5327a583ba9/out/openssl-build/install/lib -L native=/root/tools/findomain/target/release/build/ring-77a364c5511b9988/out (signal: 9, SIGKILL: kill)

**Comment by Edu4rdSHL** [comment]
Hello, that error looks like an out-of-memory issue, can you verify the RAM usage while building?

**Comment by sxcurit** [comment]
Not sure how can I do that , It runs perfectly on my laptop but throws this error on my vps.
The vps has a 1 GB Memory

**Comment by Edu4rdSHL** [comment]
Can you search in the logs for an `out-of-memory` error? Usually 1GB isn't sufficient to compile the whole project. Also you can use the precompiled binaries.

**Comment by sxcurit** [comment]
```
/var/log/syslog.1:Sep  4 10:53:49 reconpad kernel: [175801.504843] oom-kill:constraint=CONSTRAINT_NO
NE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-54
.scope,task=rustc,pid=27965,uid=0
/var/log/syslog.1:Sep  4 10:53:49 reconpad kernel: [175801.504864] Out of memory: Killed process 279
65 (rustc) total-vm:985296kB, anon-rss:678500kB, file-rss:944kB, shmem-rss:0kB, UID:0 pgtables:1848k
B oom_score_adj:0
```
seems it to be the case, works fine with precompiled binaries
Thank You <3
