### ISSUE TITLE
bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by kvsaurav** [Edu4rdSHL/findomain#118]
![image](https://user-images.githubusercontent.com/20131786/92877359-b58ce380-f428-11ea-9570-a51d459b8dec.png)

While trying to add the Api key I am getting this error

 `bash: syntax error near unexpected token `('
`

**Comment by Edu4rdSHL** [comment]
-(options) are the options you need to use with the tool, not the literal -(options) string. See `findomain --help`.
