### ISSUE TITLE
Subdomain Alerts

### ISSUE THREAD

**Issue by rudrasingh99** [Edu4rdSHL/findomain#13]
Hi

First of all awesome tool but I think it lacks one of the main purposes of the subdomain tools of alerting the user if some asset is pushed in the wild and instead user have to run the tool in some time and manually review which domain had been in the past and which one is new. Quite a hectic task but it would be cool if you integrate it in your new releases.

Cheers!

**Comment by Edu4rdSHL** [comment]
Hi, thanks. have you a idea about how should new domains be managed? It doesn't seems hard to implement but I doesn't have a big number of ideas about how to manage them. I actually have some ideas in mind:

- Create a `--news/-n ` option to show only news subdomains.
- Print they in the output as "New subdomains found" - it isn't the best idea because we're going to work with output that although it was improved in https://github.com/Edu4rdSHL/findomain/commit/bf4d8c11c599fe1421bafe71d91416b9541e4fac isn't the best way to go.

**Comment by rudrasingh99** [comment]
What about using webhooks to notify assets on a continuous basis?

It will be awesome feature to implement.

**Comment by Edu4rdSHL** [comment]
What I actually have in mind is: save results to a database and when a user ask only for new subdomains I will compare what I have actually in the database with the new results, can you explain how can be implemented your proposal?

**Comment by sumgro** [comment]
IMO, the monitoring and notification process can be both automated and on request. The user may add the domain to check for new assets to the findomain db. Then setup a cron job to run after specific intervals, and push the diff to slack-webhook. 

As for the manual, when the user requests for enumeration manually to the domain already in the list (monitored), then push only the diff to slack-webhook.

Sublert [https://github.com/yassineaboukir/sublert] uses the similar concept, while it only checks for crt.sh db for changes.

**Comment by Edu4rdSHL** [comment]
Thanks a lot @sumgro, I will implement that in a new branch and then I will let know you for tests,

**Comment by sumgro** [comment]
An idea for one time run or continuous monitoring:
- One time run to enumerate subdomains: findomain -t domain.com -o csv
- Continuous monitoring: findomain -t domain.com -m [tag for monitoring]

**Comment by Edu4rdSHL** [comment]
Hi guys, what do you prefer for the webhook to do:

1. Push the info in text/code format like:

**New subdomains found for example.com:**
```
new1.example.com
new2.example.com
newN.example.com
```
**Note:** APIs will limit the number of characters that I can send in it way.

2. Upload a file with the new subdomains inside.
3. Both.

If you have another ideas, let me know. I'm actually planing to support Slack and Discord webhooks.

**Comment by sumgr0** [comment]
Option 1 should be enough for the monitoring bit IMO

**Comment by rudrasingh99** [comment]
Hi,

Sorry for the late reply and I agree with @sumgr0 as this should be more than enough.

**Comment by Edu4rdSHL** [comment]
Hey guys, the subdomain alerts implementation is going to be pushed in develop branch tomorrow. I have a question for you, I actually have plans to send something like `No new subdomains were found for $target` if there aren't new subdomains. Do you think it's a good idea or it just should be silent? I though that it's needed to ensure that Findomain is running but doesn't found new subdomains.

**Comment by rudrasingh99** [comment]
Hi @Edu4rdSHL,

Most of the tools one such to be sublert do the same thing of notifying the user when it is unable to discover new domains.

**Comment by Edu4rdSHL** [comment]
Hello guys.

Findomain 0.4.0 is out and support subdomains monitoring. Please see https://git.io/JeZQW for details.
