### ISSUE TITLE
GLIBC_2.25 not found

### ISSUE THREAD

**Issue by sappi13** [Edu4rdSHL/findomain#15]
```
root@vultr:~/tools# ./findomain-linux
./findomain-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./findomain-linux)
root@vultr:~/tools# 
```

**Comment by Edu4rdSHL** [comment]
Hello, please use a up-to-date system or build Findomain specifically for yor system version following https://github.com/Edu4rdSHL/findomain#build-for-32-bits-or-another-platform
