### ISSUE TITLE
DNS public resolvers

### ISSUE THREAD

**Issue by ch0wn** [Edu4rdSHL/findomain#19]
Hi,

In order to speed the DNS resolving, you can look into using using public resolvers (massdns like).
However the resolvers list must be kept fresh, possibly by using something like this https://github.com/Abss0x7tbh/bass

Thanks!

**Comment by Edu4rdSHL** [comment]
Hi, thanks for the feedback. Findomain is actually using public resolvers, what I can do is give to the user the possibility to set their own DNS resolvers instead of Findomain doing that work of kept fresh resolvers itself.

**Comment by ZeroDot1** [comment]
With the new Brutforce option it should also be possible to use a list of resolvers.

example: 

`findomain -w Words.txt -customresolvers resolvers.txt -r -t domain.com`

```
resolvers.txt
IPv4 and IPv6 Resolvers
```
The resolvers in the list should always be used randomly.

For example, if you specify a domain list via -f List.txt, you should not always use the same resolver.
It should always use a different resolver for each domain.

**Comment by chppppp** [comment]
Any update? Would love to use a custom list of resolvers. Thanks!

**Comment by Edu4rdSHL** [comment]
It's the next feature to implement in the plus version.

**Comment by Edu4rdSHL** [comment]
Hey guys, this was implemented in plus version.
