### ISSUE TITLE
Create file with an ouput

### ISSUE THREAD

**Issue by Cosaquee** [Edu4rdSHL/findomain#2]
Hi! This tools is really handy but right now it is hard to consume the output in some programmatic way. It would be really cool if we could specify some sort of output file that would be created with results, it could be a JSON or CSV file, probably a txt file with list of subdomain would be also useful.

What do you think?

**Comment by Edu4rdSHL** [comment]
Hello. Sure, I will do that soon and add support for some file formats.

Thanks for the feedback.
