### ISSUE TITLE
Save only resolved subdomains

### ISSUE THREAD

**Issue by ch0wn** [Edu4rdSHL/findomain#20]
Hi,

Would be great to have the option to save a list of subdomains which are live (resolved).
That would be useful in automation, as the output can be fed into other tools without cutting/grepping first.

Thanks!

**Comment by ch0wn** [comment]
What I mean is, after the enumeration is done, there is the output looking like this:

dead-sub.example.com,No IP address found
live-sub.example.com,1.2.3.4

Now I have to remove the lines with "no IP address" and then cut the column with the IPs, leaving subdomains which are resolved only.
Does it make sense?

**Comment by Edu4rdSHL** [comment]
Fixed via https://github.com/Edu4rdSHL/findomain/commit/8765694d50fea5226d85eb69330b586011938b81
