### ISSUE TITLE
Output single file

### ISSUE THREAD

**Issue by ch0wn** [Edu4rdSHL/findomain#21]
Hi,

Would be great to have the option of storing the output in a single file, for better handling in automation. Currently when scanning a massive list of domains it outputs hundreds/thousands .txt files.

Thanks!

**Comment by Edu4rdSHL** [comment]
Hello, yeah I will add a new `--single-output` option to use a personalized file name and format and save all data here, that's what I have actually in mind. let me know if it's fine in your opinion.

**Comment by ch0wn** [comment]
That would be just fine, thank you.

**Comment by Edu4rdSHL** [comment]
Fixed.
