### ISSUE TITLE
Consider using structopt

### ISSUE THREAD

**Issue by kpcyrd** [Edu4rdSHL/findomain#23]
You're currently using clap directly, in case you aren't aware of it you can give [structopt] a try, it makes it easier to access the parsed arguments. Real life example can be found [here].

If you're interested I can prepare a PR for this.

[structopt]: https://crates.io/crates/structopt
[here]: https://github.com/kpcyrd/sn0int/blob/master/src/args.rs

**Comment by Edu4rdSHL** [comment]
Hello @kpcyrd. What will be the benefits between the actual implementation and using structopt?  I saw that when I started developing Findomain but I though it isn't necessary to use another crate for managing tool arguments when they aren't much.

**Comment by Edu4rdSHL** [comment]
Hello mate, I have simplified the run() function to not continue increasing the code but making the conditions simples and reliables  checking the variables one time only before being passed to the functions. Now we just have two calls to functions into run() as you can see in https://github.com/Edu4rdSHL/findomain/blob/8765694d50fea5226d85eb69330b586011938b81/src/main.rs#L41-L60.

Thanks a lot for the suggestion but I consider it isn't needed for now, clap is working just fine and I don't want more dependencies there.
