### ISSUE TITLE
Error: IO error

### ISSUE THREAD

**Issue by toplul** [Edu4rdSHL/findomain#26]
Hi.

Thanks for your work.

I have some problem on Windows Server, Windows 7, Kali Linux.

Pic related.

White IP, no firewall, stable connection, admin rights.

Thanks.
![issue](https://user-images.githubusercontent.com/55960115/65838722-d559f300-e30e-11e9-9382-a1422c0e489f.jpg)

**Comment by Edu4rdSHL** [comment]
Hello @toplul. You need to have PostgreSQL installed in your machine or a remote server in order to use the `-m` flag. Please see https://github.com/Edu4rdSHL/findomain/blob/master/README.md#subdomains-monitoring
