### ISSUE TITLE
Not able to publish to slack webhook

### ISSUE THREAD

**Issue by sumgr0** [Edu4rdSHL/findomain#27]
Thanks for the big update to allow monitoring using the tool.

When trying to monitor single domain or a file using -f and publish the result to slack, getting the below error:

An error occurred when Findomain tried to publish the data to the following webhook https://hooks.slack.com/services/XXXXXXXXXX.                                                                                                                                                           
Error description: 400 Bad Request

The same webhook is working with other message or manually pushing a test message.

**Comment by Edu4rdSHL** [comment]
Hello @sumgr0, thanks for the feedback.

I'm actually sending the message payload formatted according to https://api.slack.com/incoming-webhooks#posting_with_webhooks in the format `{"text": "subdomains information here"}` as you can see in https://github.com/Edu4rdSHL/findomain/blob/b07a491b49f3616ba0a7ee0b930f5daa3f15e703/src/lib.rs#L673-L679 I don't have a Slack environment to test and I only have tested in Discord (that works in [a similar way](https://discordapp.com/developers/docs/resources/webhook#execute-webhook))  and it's working fine. I have not idea why it isn't working, I've seen another examples and do the same thing I'm doing. Can you write here how you send the data using a `curl` one-line for example?

**Comment by sumgr0** [comment]
Hi @Edu4rdSHL,

Here is how I currently use slack-webhook for an automation I created:

 (echo "$LINE") && curl -X POST --silent --data-urlencode "payload={\"text\": \"$(echo $LINE)\"}" "$S_HOOK"

Hope this is helpful.

**Comment by Edu4rdSHL** [comment]
Thanks @sumgr0. Is possible for you to give me a Slack webhook and invite me to the Slack server in a Twitter DM for tests? Still reading the documentation and can't figure what's wrong.

**Comment by sumgr0** [comment]
Sent a DM for slack username. Please check

**Comment by Edu4rdSHL** [comment]
Hi @sumgr0 it has been fixed. Please check out the 0.4.1 release. https://github.com/Edu4rdSHL/findomain/releases/tag/0.4.1

**Comment by sumgr0** [comment]
Thanks for the quick update @Edu4rdSHL 

Really appreciate the dedication and focus. Findomain is really improved my workflow.
