### ISSUE TITLE
List of monitored domains [Feature Request]

### ISSUE THREAD

**Issue by sumgr0** [Edu4rdSHL/findomain#28]
A quick check after the 0.4.1 update, there is no option/message to check if the domain is already monitored. A tag -ml (monitored list) or just -l (list) to get the list of monitored domains would be really handy in the long run.

Additionally, how frequently does findomain check for new domains and passes to the webhook?

**Comment by Edu4rdSHL** [comment]
Hi, @sumgr0.

> A quick check after the 0.4.1 update, there is no option/message to check if the domain is already monitored. A tag -ml (monitored list) or just -l (list) to get the list of monitored domains would be really handy in the long run.

The list of monitored subdomains is defined by the user, it can be a list of domains into a text file or only a domain using the -m option. When a domain is removed from the text file it automatically leave of the monitoring range and when a new is added join to the monitoring range.

> Additionally, how frequently does findomain check for new domains and passes to the webhook?

That's a user configuration, you can use cron or any job scheduler for doing that and check when you want.

Findomain is a subdomains enumeration tool, not a job scheduler. There are a lot of awesome tools that can be used specifically for that purpose in any OS.

See https://github.com/Edu4rdSHL/findomain/commit/866cfcdaee156bc7d539d95af19aa863f18e5dea
