### ISSUE TITLE
[Feature Request] Support for Mac OS

### ISSUE THREAD

**Issue by evilwing** [Edu4rdSHL/findomain#3]
exec format error: findomain

**Comment by evilwing** [comment]
macosx

**Comment by Edu4rdSHL** [comment]
Hello, the tool actually only runs in GNU/Linux systems. I will add support for Mac OS soon.

**Comment by Edu4rdSHL** [comment]
The release is ready, I will push it in a couple of minutes.

**Comment by Edu4rdSHL** [comment]
Fixed via https://github.com/Edu4rdSHL/findomain/commit/6cc8a1950d4e2098598cafa73d05d1a10cc36f37
