### ISSUE TITLE
 Option to save new domains found in a txt file when monitoring

### ISSUE THREAD

**Issue by ch0wn** [Edu4rdSHL/findomain#30]
Hello,

Would it be possible to save new domains found in a text file also when using the monitor mode?
So just the new ones, after the first iteration. That would be helpful when automating the flow between multiple tools.
Many thanks!

**Comment by Edu4rdSHL** [comment]
Hello, @ch0wn. Yes, that's possible and I have considered that option before including the monitoring feature but didn't include it on purpose. The writing to output file process will be the same that's used actually with the `-o` and `-u` flags. A backup of the existing file will be created when new subdomains are found. Is it fine?

Thanks for the feedback.

**Comment by sumgr0** [comment]
Suggestion: when the domains are monitored, generate a file [existing subdomains] from the db and then when new subdomains are discovered, create a new file [new_subdomains.txt]. These will be appended to the existing list during the next run on the monitored domains.

**Comment by Edu4rdSHL** [comment]
Thanks @sumgr0 for the suggestion. Anyways we need to consider what filenames will be used for new subdomains and existing subdomains when:

* Read a domain using the -t option and the -o option (automatic and per target filename) is used.
* Read a list of domains using the -f option and the -o option (automatic and per target filename) is used.
* Read a domain using the -t option and the -u option (personalized and unique output filename) is used.
* Read a list of domains using the -f option and the -u option (personalized and unique output filename) is used.

Will be good if you give me ideas about how to manage every case.

**Comment by ch0wn** [comment]
Hi @Edu4rdSHL, it is fine with me. Thank you!

**Comment by sumgr0** [comment]
IMO and suggestion for handling the file naming could be simplified:
- Allow only automatic file name option **-o** tag with **-t** for single target domain
- Allow both **-o** & **-u** for output with -f option with domain names list

For monitored domains, during the 2nd run and later of -m (manually or using scheduler):
- if **-t** is used, current list of subdomains in db **[current_db.txt]** + **[new_target.txt]** for the target
- if **-f** is used, current list of subdomains in db **[current_db.txt]**+ **[new_subdomains.txt]** for the list

**Comment by Edu4rdSHL** [comment]
I have a idea now. Sincerely I want to support the same things for both `-t` and `-f` options.

* If the `-o` option is used, use the following filename: for current subdomains: `target-string+current_subdomains.txt`, for new subdomains: `target-string+new_subdomains.txt`
* If the `-u` option is used: for current subdomains `user filename+current_subdomains.txt` for the new `user filename+new_subdomains.txt`

And in every run the data of new subdomains will be copied to existing subdomains if new subdomains are > 0.

Please let me know if it's fine.

**Comment by sumgr0** [comment]
This looks like workable solution.

**Comment by Edu4rdSHL** [comment]
Hello guys, it has been implemented but the file name will be automatic in the format target-string.new_subdomains.txt and target-string.new_subdomains.old.txt for backup files.

For example.com and example.org:

New subdomains: example.com.new_subdomains.txt, example.org.new_subdomains.txt
New subdomains backup file: example.com.new_subdomains.old.txt, example.org.new_subdomains.old.txt

Sorry to no implement it in the original way I thinked but sincerely it's a bit hard to do because the -m option wasn't with output files in mind when it was created.
