### ISSUE TITLE
Problems with monitoring

### ISSUE THREAD

**Issue by Dujunayan** [Edu4rdSHL/findomain#32]
hello , i already try a lot but i have a lot of issue on monitoring , can someone give the process 
some probleme i got :
1* i already export but i got this message
1- You need to set at least one webhook variable. For Discord set the findomain_discord_webhook system variable and for Slack set the findomain_slack_webhook variable. Exiting.

2- psql: FATAL:  Peer authentication failed for user "postgres"

**Comment by Edu4rdSHL** [comment]
Hello @Dujunayan.

1. What OS are you using?
2. How are you exporting the variable?
3. How are you configuring the PostgreSQL options?

**Comment by Dujunayan** [comment]
one of my friend he helped me , thank you !
but on discord i just got 30 subdomain when there's more

Le dim. 6 oct. 2019 à 01:24, Eduard Tolosa <notifications@github.com> a
écrit :

**Comment by Edu4rdSHL** [comment]
Findomain put in Discord the number of unique subdomains he found, if it put there 30 is because he found 30. Will be good is you provides more info about the "i just got 30 subdomain when there's more". I'm Edu4rdSHL#5506 in Discord.

**Comment by Dujunayan** [comment]
exemple 
: findomain_discord_webhook='https://discordapp.com/api/webhooks/xxxxxx'  findomain -t google.com -m --postgres-password xxxxx
 the result is 33000 . 
on discord i got just 55 subdomain !!

thanks for helping

**Comment by Edu4rdSHL** [comment]
I understand. That's because Discord had a limit of 2000 characters per message and I have to send only the fisrt subdomains in the message. I will try to send they in separated messages and see if Discord supports that.

Thanks.

**Comment by Dujunayan** [comment]
i think it's okay if we just made the webhook for new subdomain, not for listing all subdomain on discrod, weird xD !!

**Comment by Edu4rdSHL** [comment]
The Discord is just for new subdomains, if the tool is runned first time all subdomains found are new subdomains because nothing is in the database. After first run it will effectively send only new subdomains.

**Comment by Dujunayan** [comment]
Great work
