### ISSUE TITLE
add quiet mode 

### ISSUE THREAD

**Issue by 0xibram** [Edu4rdSHL/findomain#34]
Hi,
Findomain is a very verbose tool. It outputs a lot of things to stdout that make automation/piping hard. For example, I can't do something like `findomain -t example.com -r | httprobe`. 

It would be really nice if you can add a quiet mode with a `--quiet/-q` flag that will make the tool output subdomains only without any of the extra text such as `Searching in the * API` and `A total of * subdomains were found` etc. Just subdomains!

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the feedback. Will be implemented for the next release.
