### ISSUE TITLE
Add hability to select the DNS to use.

### ISSUE THREAD

**Issue by Edu4rdSHL** [Edu4rdSHL/findomain#40]
Actually you can't choose what DNS resolver use, Findomain uses system configuration by default, if it fails to read the configuration then try to use Cloudflare, if it fails then Quad9 and finally Google.

The implementation will make possible a user's choice to select what DNS to use. The option will be `--dns cloudflare/quad9/google` and if not option is specified then use system's configuration. It will also works for #37.

**Comment by ZeroDot1** [comment]
You should also add the possibility that the user can use a custom DNS resolver.

**Comment by Edu4rdSHL** [comment]
See https://github.com/Edu4rdSHL/findomain/issues/19

**Comment by ZeroDot1** [comment]
Okay, perfect.

**Comment by Edu4rdSHL** [comment]
Fixed in https://github.com/Edu4rdSHL/findomain/commit/604d0a1ffb40731aa3df01fd5540649bce777012
