### ISSUE TITLE
Add the possibility to use a configuration file

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#41]
A configuration file would be very useful to store tokens and other settings (E.g. DNS settings).

**Comment by eugui** [comment]
why I'm getting this error?
*mac

MBP:Security xxp$ findomain_spyse_token="TsKL5..." findomain-osx -(options)
-bash: syntax error near unexpected token `('
MBP:Security xxp$ 
MBP:Security xxp$ 
MBP:Security xxp$ findomain_spyse_token="TsKL5..." findomain -(options)
-bash: syntax error near unexpected token `('
MBP:Security xxp$

**Comment by ZeroDot1** [comment]
Example configuration file:

Default configuration path:
`'/home/user/.config/findomain/config.cfg'`

config.cfg

```json
//APISettings

SecurityTrails:
User=""
Pass=""
APIKey=""

VirusTotal:
User=""
Pass=""
APIKey=""

Facebook:
User=""
Pass=""
APIKey=""

// Findomainsettings
Findomain: 
exclude = facebook,virustotal
threads 100
ipv6-only = yes / no
ip = yes / no
enable-dot  = yes / no
file /user/input.txt
unique-output /user/output.txt
quiet = yes / no
resolved  = yes / no
target domian1.com domian2.com
resolver <IPv6 : IPv4> // 1.1.1.1,8.8.8.8
```

**Comment by Edu4rdSHL** [comment]
It will be a TOML and also is under development, it hasn't been added because I need to provide compatibility with the old way for existing setups at least for six months and that's a bit tricky. 

It will be added in ~2 weeks.
