### ISSUE TITLE
Import keys - Error

### ISSUE THREAD

**Issue by eugui** [Edu4rdSHL/findomain#42]
why I'm getting this error? I use mac.

MBP:Security xxp$ ./findomain-osx -h
findomain 0.8.0
Eduard Tolosa edu4rdshl@protonmail.com
The fastest and cross-platform subdomain enumerator, don't waste your time.

MBP:Security xxp$ findomain_spyse_token="TsKL5..." findomain-osx -(options)
-bash: syntax error near unexpected token (' 
MBP:Security xxp$ 
MBP:Security xxp$ 
MBP:Security xxp$ findomain_spyse_token="TsKL5..." findomain -(options) 
-bash: syntax error near unexpected token ('
MBP:Security xxp$

**Comment by Edu4rdSHL** [comment]
Because -(options) is an invalid argument. With -(options) in the documentation I mean the options that findomain have. Try:

findomain_spyse_token="yourtoken" findomain -t example.com

**Comment by eugui** [comment]
I don't know if worked.

MBP:Security xxp$
MBP:Security xxp$ findomain_spyse_token="TsKL5..." findomain -t xxx.com
-bash: findomain: command not found
MBP:Security xxp$ findomain_spyse_token="TsKL5..." findomain-osx -t xxx.com
-bash: findomain-osx: command not found
MBP:Security xxp$ findomain_spyse_token="TsKL5..." ./findomain-osx -t xxx.com

Target ==> xxx.com

Searching in the Sublist3r API... 🔍
Searching in the CertSpotter API... 🔍
Searching in the Crtsh database API... 🔍
Searching in the Virustotal API... 🔍
Searching in the Facebook API... 🔍
Searching in the Spyse API... 🔍
Searching in the Threadcrowd API... 🔍
Searching in the Bufferover API... 🔍
Searching in the AnubisDB API... 🔍
❌ An error occurred while parsing the JSON obtained from the Facebook API. Error description: JSON error.

**Comment by Edu4rdSHL** [comment]
Yes, it worked.

**Comment by eugui** [comment]
I don't know if the "findomain_spyse_token" is valid. If I test using a wrong and valid token the result is always the same.

**Comment by Edu4rdSHL** [comment]
Please read [the documentation](https://github.com/Edu4rdSHL/findomain#how-it-works).

> APIs marked with * can optionally be used with an access token, create one if you start experiencing problems with that APIs.
