### ISSUE TITLE
I downloaded the binary, but how do I dock the api?

### ISSUE THREAD

**Issue by laowang1026** [Edu4rdSHL/findomain#43]
I downloaded the binary, but how do I dock the api?

**Comment by laowang1026** [comment]
![image](https://user-images.githubusercontent.com/45323129/68932897-7cff8780-07ce-11ea-9009-32d3d78419f3.png)

**Comment by Edu4rdSHL** [comment]
You don't need to do anything there, Findomain dock the APIs automatically.

**Comment by laowang1026** [comment]
? An error occurred while parsing the JSON obtained from the Bufferover API. Error description: JSON error.
? A error has occurred while connecting to the Crtsh database. Error: IO error. Trying the API method...
Searching in the Crtsh API... ??
? An error occurred while parsing the JSON obtained from the Threatcrowd API. Error description: JSON error.
? An error occurred while parsing the JSON obtained from the Sublist3r API. Error description: JSON error.

**Comment by laowang1026** [comment]
It broke the error like this
