### ISSUE TITLE
Add Support for: archive.org ( #7 )

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#44]
I just looked at the WaybackMachine API, that should work with the following URLs...
http://web.archive.org/cdx/search/cdx?url=example.com*&output=txt
http://web.archive.org/cdx/search/cdx?url=example.com*&output=json
http://web.archive.org/cdx/search/cdx?url=example.com*&output=txt&limit=999999
https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server#filtering
http://web.archive.org/cdx/search/cdx?url=*.google.com&output=json&collapse=urlkey

**Comment by Edu4rdSHL** [comment]
They doesn't have any subdomains field but URLs instead.
