### ISSUE TITLE
Error Compiling on tokio-rustls v0.10.2

### ISSUE THREAD

**Issue by dzhenway** [Edu4rdSHL/findomain#46]
Hi,

I got error when try `cargo build --release`

```
error: enum variants on type aliases are experimental
   --> /home/wayc0de/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-rustls-0.10.2/src/lib.rs:260:9
    |
260 |         Self::Client(s)
    |         ^^^^^^^^^^^^

error: enum variants on type aliases are experimental
   --> /home/wayc0de/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-rustls-0.10.2/src/lib.rs:266:9
    |
266 |         Self::Server(s)
    |         ^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `tokio-rustls`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Hope you can help me

Thank you

**Comment by Edu4rdSHL** [comment]
You need to update the Rust version to latest stable (1.39.0). What's the output for `rustc -V`? If you have a version less than 1.39.0 then you need to update it.

**Comment by Edu4rdSHL** [comment]
Are you sure the `cargo` command that you are using when building is from $HOME/.cargo/bin ? Use `command -v rustc`

**Comment by dzhenway** [comment]
```
wayc0de@DESKTOP-9C0TVKV:~$ command -v rustc
/usr/bin/rustc
```

**Comment by Edu4rdSHL** [comment]
That's the problem, when you run `cargo` you're using the binary installed in `/usr/bin` instead of `$HOME/.cargo/bin`.

Uninstall the package that owns the binary in /usr/bin, add `$HOME/.cargo/bin` to your PATH and try again or just use a full qualified PATH to call the cargo binary.

**Comment by dzhenway** [comment]
solved

I add this to my .bashrc

`export PATH="$HOME/.cargo/bin:$PATH"`

thank you sir
