### ISSUE TITLE
Parsing Error facebook Api

### ISSUE THREAD

**Issue by marcelo321** [Edu4rdSHL/findomain#48]
I get this error when running the tool
 
   An error occurred while parsing the JSON obtained from the Facebook API. Error description: JSON error.

**Comment by Edu4rdSHL** [comment]
Hello, please use a private Facebook token. The error occurs because the built-in tokens reach the number of requests. Read the documentation to see [how to set up it](https://github.com/Edu4rdSHL/findomain/blob/master/README.md#configuring-the-facebook-api).
