### ISSUE TITLE
Make JSON errors more verbose

### ISSUE THREAD

**Issue by dee-see** [Edu4rdSHL/findomain#49]
I get a lot of `An error occurred while parsing the JSON obtained from the {} API. Error description: {}.` errors and I'd love to see the "JSON" (I suspect findomain is receiving some sort of rate-limiting error page...) that caused the error.

Thanks for the great tool!

**Comment by Edu4rdSHL** [comment]
Hello, @dee-see. You shouldn't worry about that error, as described in the commit it's caused by:

> Some APIs fail because generic HTTP errors like 504 Bad Gateway, 429 Too Many Requests, etc. These API's response body was being processed trying to deserialize them and was causing fake JSON errors.

That means the error isn't a JSON error but HTTP error from the server. The solution:

> Now Findomain just try to deserilize those API's body that have returned a HTTP 200 status code but also let know to the user what API have failed and what error message returned.

Also the verbose for real JSON errors (if they came to exist) has been increased.

Thank you.
