### ISSUE TITLE
Option to turn off notifications when no subdomain found

### ISSUE THREAD

**Issue by uBadRequest** [Edu4rdSHL/findomain#50]
Hello!

I have so many subdomains that discord gets flooded with no new subdomains found for ...

Also, would be cool if we could add the IP addresses that they resolve to!

**Comment by Edu4rdSHL** [comment]
Hello, 

1. Do you think there should be a flag to stop findomain pushing to webhooks when there aren't new subdomains?
2. You mean push the IP address to webhooks?

**Comment by sumgr0** [comment]
The point no.1 is really a good option if that's possible. That way findomain pushes the notification only when there are new subdomains discovered, since the message No new subdomains, has no positive value.
Another option, if there could only be one push when no new subdomains are discovered for a list of monitored items, that way one can know if findomain process is still alive.

**Comment by uBadRequest** [comment]
> The point no.1 is really a good option if that's possible. That way findomain pushes the notification only when there are new subdomains discovered, since the message No new subdomains, has no positive value.
> Another option, if there could only be one push when no new subdomains are discovered for a list of monitored items, that way one can know if findomain process is still alive.

Yeah, @sumgr0  that would be a good idea!



> Hello,
> 
> 1. ~Do you think there should be a flag to stop findomain pushing to webhooks when there aren't new subdomains?~ Edit: sorry, it's clear.
> 2. You mean push the IP address to webhooks?

Yeah, that might need to be a different request for enhancement but I am currently trying to create a work flow that monitors what IP addresses the discovered subdomains resolve to and alerting when they change. Specifically interested in subdomains that don't resolve at all or resolve to an internal IP, so that when they start resolving to a public IP, I can look into it.  @Edu4rdSHL

**Comment by Edu4rdSHL** [comment]
Hey @sumgr0, @uBadRequest . The point of the "No new subdomains were found" message was to let the user to know that the Findomain process is running.
> Another option, if there could only be one push when no new subdomains are discovered for a list of monitored items, that way one can know if findomain process is still alive.

I don't think we should worry for Findomain failing to push or something, it's mature enough to need to send that kind of notices. If it runs the first time then it will run 1 million of times smoothly. I'm going to implement a flag that when enabled just don't push `No subdomains where found for: $target` to webhooks.
>Yeah, that might need to be a different request for enhancement but I am currently trying to create a work flow that monitors what IP addresses the discovered subdomains resolve to and alerting when they change. Specifically interested in subdomains that don't resolve at all or resolve to an internal IP, so that when they start resolving to a public IP, I can look into it. @Edu4rdSHL

Definitely, it needs another request for enhancement. By the way, currently Findomain can discover subdomain's IPs and save they to a file, is that not enough to perform your monitoring work?

**Comment by Edu4rdSHL** [comment]
Fixed in https://github.com/Edu4rdSHL/findomain/commit/ea230986c7a0ad712ed7cea1e5e6ba0b5c96fe00. Now by default Findomain only push data to webhooks when there are new subdomains. If you want the old behavior then use the `--aempty` flag.
