### ISSUE TITLE
Add timestamp column to the pgsql database table

### ISSUE THREAD

**Issue by xtrmbuster** [Edu4rdSHL/findomain#52]
Good job men !

I don't know the language which it used to build it to help you but can you add a column with the timestamp of the execution, could be like the date with hours like YYYY-MM-DD-hh-mm.

It could be useful.

Thanks !

**Comment by Edu4rdSHL** [comment]
Hello, what's the purpose of that? Also, did you mean the date when the subdomain is pushed to database?

**Comment by xtrmbuster** [comment]
Yes that's it. 

You can use it to sort result later by scripting in order to dirbruteforcing the last subdomains

**Comment by Edu4rdSHL** [comment]
Hello,

I have added what you want and also some kind of "migration"  step to modify existing old database schema to match new scheme (to avoid users having to drop databases and lost all your data). https://github.com/Edu4rdSHL/findomain/blob/db67002bc0e51bf64872f11be2b48fc320a3908c/src/lib.rs#L730-L739

If you want to test the new features (like @sumgr0 does) please see the [documentation for developers](https://github.com/Edu4rdSHL/findomain/tree/develop#development). Will be good if you want to be a beta tester.

**Comment by xtrmbuster** [comment]
Hey ! 

Thanks, it works fine but the timestamp need to be formated to not be so long 

40 | email.booztlet.com       | 2020-01-17 21:20:35**.500969+01**

**Comment by Edu4rdSHL** [comment]
Why se need to care about that? We dont use that data for anything. If you want to sort by date just use: `SELECT name FROM subdomains  WHERE name like '%.domain.com' ORDER BY timestamp DESC` and the subdomains are sorted from newest to oldest or change DESC by ASC is you want otherwise.

**Comment by xtrmbuster** [comment]
I understand your point of view, I'll see further if it's really important.

For me, it's in order to extract this by day for example, but maybe we can do this in another manner :) 

Thanks for your work, i'm going to see it in 2 weeks

**Comment by Edu4rdSHL** [comment]
If you want to extract by day, just use `SELECT name FROM subdomains WHERE DATE(timestamp) = '2020-01-17';` if you want subdomains pushed to database in '2020-01-17'.
