### ISSUE TITLE
[BUG]: Target is invalid

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#53]
Hi @Edu4rdSHL,
Thanks for the last update, it looks good, but unfortunately there is an error.

0. 
```
git clone https://github.com/Edu4rdSHL/findomain.git -b develop # Only the develop branch is needed
cd '/home/user/findomain'
git pull
cargo build --release
sudo cp target/release/findomain /usr/bin/
cd
```

1. `$ findomain -f "/URLsToScan.txt" -u '/URLsToScanDONE.txt'`

2. Error: `Target is invalid, please try again.`

ExampleURLs in the file:

```
0769.it
1337pool.net
1dig.pro
1isolution.com
1stminingpool.com
```
When the error occurs, the program stops working.

**Comment by Edu4rdSHL** [comment]
Hello @ZeroDot1, it have been fixed. The error was introduced in 0.9.8 due to a bad  check but it's now fixed.
