### ISSUE TITLE
Agregar estado de respuesta y tecnologia

### ISSUE THREAD

**Issue by Lokillo20** [Edu4rdSHL/findomain#54]
Estaria bueno agregar un status response y tecnologia usada (un fingerprint rapido), como lo hace la herramienta knockpy, esta herramienta te brinda codigos de estado (400,200,etc) tipo (host,alias) ip, dominio y servidor (apache, iis, etc).
Gracias por tu herramienta, se convirtio en mi favorita, saludos desde Argentina

**Comment by Edu4rdSHL** [comment]
Hola, gracias. 

1. Findomain es un enumerador de subdominios, no un escáner de puertos, para eso ya existe nmap o masscan. 

En la versión 1.0.0 Findomain incorporará un escáner de puertos abiertos que funcionará de manera asíncrona y podrá escanear unos 1000 puertos por segundo pero será solo un escáner para ver los puertos abiertos, no para detectar versiones de software o software usado.

2. Los estados de respuesta que mencionas son HTTP, Findomain los únicos recursos HTTP que consume son las APIs y ya tienen implementados los códigos de respuesta. ¿A qué más se le debería implementar?

**Comment by Lokillo20** [comment]
No esperaba un escaner de puertos ,simplemente que realice una comprobacion al puerto 80 y 443 que son los mas comunes respecto a protocolo web, si el subdominio is alive, entonces hacer una request web y extrae el tipo de servidor (si aparece en la request de respuesta obvio). 
Lo que hago actualmente es hacer usar el output de findomain y lo paso por otra tool llamada httprobe, y esta me devuelve las q tienen los puertos 80 y 443 (creo que 8080 tb), con ese resultado utilizo otra tool que me simplifica datos como tipo de servidor y demas. Te dejo una captura de como lo hace knockpy, pasa q el motor de busqueda de knockpy no es tan bueno como findomain. Saludos! 
![IMG_20200120_153934](https://user-images.githubusercontent.com/48301463/72750273-29793380-3b9b-11ea-877f-57b194284dab.jpg)
