### ISSUE TITLE
Remove the emoticons

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#55]
The emoticons can not be displayed correctly in many consoles even if the correct font is installed. So I recommend to remove the emoticons.

Screenshot:
![Bildschirmfoto vom 2020-01-24 18-38-18](https://user-images.githubusercontent.com/28985171/73090462-547fc200-3ed0-11ea-8513-83f94a24fb69.png)

**Comment by Edu4rdSHL** [comment]
Hello, though you can just use quiet mode.

**Comment by ZeroDot1** [comment]
Hm, good idea :+1:
