### ISSUE TITLE
Add Support for SecurityTrails

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#56]
See: https://securitytrails.com/blog/subdomain-finder 
And: https://github.com/secops4thewin/securitytrails-python/blob/master/securitytrails.py  

* Example
`https://api.securitytrails.com/v1/domain/github.com/subdomains?apikey=YOUR.API.KEY.HERE`

**Comment by Edu4rdSHL** [comment]
Will be added soon.

**Comment by ZeroDot1** [comment]
Many thanks, here is an alternative URL.
https://securitytrails.com/list/apex_domain/github.com

**Comment by Edu4rdSHL** [comment]
Fixed in https://github.com/Edu4rdSHL/findomain/commit/892ba983373bfc507d1e0ea9a36429641a42a126
