### ISSUE TITLE
Add Support for: threatminer.org

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#57]
* Example:
https://api.threatminer.org/v2/domain.php?q=github.com&api=True&rt=5

**Comment by Edu4rdSHL** [comment]
Thanks.

**Comment by Edu4rdSHL** [comment]
Fixed in https://github.com/Edu4rdSHL/findomain/commit/892ba983373bfc507d1e0ea9a36429641a42a126
