### ISSUE TITLE
Add an option to exclude sources

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#59]
If you cannot use a specific source, it is very useful to exclude these sources directly to save time when scanning for subdomains.

* Example: 
`findomain --threads 100 -ex facebook virustotal -q -f "/URLsToScan.txt" -u '/URLsToScanDONE.txt'`

* Note: `-ex` for excluding sources.

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the suggestion. 
By the way it's already under development and will be added soon.

**Comment by ZeroDot1** [comment]
Thank you, that's very helpful.
