### ISSUE TITLE
Add IP to notification while monitoring

### ISSUE THREAD

**Issue by uBadRequest** [Edu4rdSHL/findomain#60]
Could we get an option to add what a discovered subdomain is resolving to in the notification that is send to discord?

**Comment by Edu4rdSHL** [comment]
Hello, I will send the resolved domains in the format `domain.tld,IP address`. Have in mind that enabling it option you will only got there non NX domains (only exisintg ones), that's how the current resolver works: if `IP == NULL`, don't return anything.

**Comment by uBadRequest** [comment]
Yes thats fine. It will help me easily distinguish between domains that have been registered but aren't pointing anywhere.

How FindDomain is currently designed, how easy would it be to send a notification if a found subdomain starts pointing to a CNAME or IP address?

**Comment by Edu4rdSHL** [comment]
> How FindDomain is currently designed, how easy would it be to send a notification if a found subdomain starts pointing to a CNAME or IP address?

Findomain is designed  in a very modular way, every step is done by a independent and optimized function for that step specifically but at same time every function can work together with another function without any problem. The asynchronous resolver is:

 https://github.com/Edu4rdSHL/findomain/blob/3e5fd138584341ee1563db78bb0ee9a10be7867a/src/lib.rs#L255-L276

Currently the resolver **is only capable of discover IP, not CNAME**, it isn't hard to implement but I need to add a new feature, then I can work with CNAME. Talking about the possibility to send the `domain.tld,ip` format to webhooks, isn't hard, I need to add a couple of lines to do that but sincerely is more a logic implementation.

So, I'm going to delete "CNAME" for the issue title and if you want to work with CNAME record, open another request for enhancement.

**Comment by uBadRequest** [comment]
Would it be easier to just insert the IP address in the database? I'm really interested in finding domains that suddenly start resolving to an IP addresses. Maybe create two columns, one for the date modified and then the IP. Would be cool to track if an IP address changes or just record changes, like it starts pointing to a CNAME but theres probably alot that are going to be load balanced and change IP addresses often...

**Comment by Edu4rdSHL** [comment]
It feature have been implemented in Findomain+ version. To know more about it see https://twitter.com/Edu4rdSHL/status/1229585761059721220?s=19

Proof: https://twitter.com/Edu4rdSHL/status/1233239614745391104?s=19
