### ISSUE TITLE
Slack webhook timeout error

### ISSUE THREAD

**Issue by sumgr0** [Edu4rdSHL/findomain#61]
Hi,
I've recently noticed quite a bit of timeout for the slack webhook. This is both when using high number of threads like 200 and also while running it in default mode.

**Comment by Edu4rdSHL** [comment]
Hello, I just tested 1 minute ago and it's working fine. It's an issue between your ISP and Slack. 

Try running findomain with a proxy, TOR, VPN or something.

It isn't a Findomain issue.
