### ISSUE TITLE
Bug: Output file is deleted / overwritten after each domain.

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#62]
Since the last update there is the problem that the output file is overwritten after each new domain that is checked.
Normally all results should be written to one file.

Example: 

`findomain --threads 10 -q -f "/URLsToScan.txt" -u /URLsToScanDONE.txt`

![Bildschirmfoto vom 2020-02-07 17-50-31](https://user-images.githubusercontent.com/28985171/74048366-f96ac680-49c9-11ea-9dab-858b9704a527.png)

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the report. What options are you using?

**Comment by ZeroDot1** [comment]
I have used findomain as in the following example.

`findomain --threads 60 -q -f "/URLsToScan.txt" -u "/URLsToScanDONE.txt"`

**Comment by Edu4rdSHL** [comment]
Hello, thanks for reporting, I have reproduced it. Fix will be today in the night.

**Comment by ZeroDot1** [comment]
Thank you very much.

**Comment by Edu4rdSHL** [comment]
Thanks for the report! I forget to update the match section for that parameter. :/
