### ISSUE TITLE
Discord webhook command-line option 

### ISSUE THREAD

**Issue by xtrmbuster** [Edu4rdSHL/findomain#65]
Hey, 

I didn't find the way to pass the webhook key in the commandline without using the environment variable that your purposed.

Can you ?

Thanks ;) helpful for automation cause the profile var doesn't really works with crontab

**Comment by Edu4rdSHL** [comment]
Hellp. It will be fixed when configuration file is used. See #41.

Still for automation you can execute:

```
findomain_slack_webhook='your_webhook_url' /path/to/findomain -options
```

Or create a script with the syntax mentioned above and then simply execute the script.
