### ISSUE TITLE
Banned from Apis when mass enumerating subdomains

### ISSUE THREAD

**Issue by marcelo321** [Edu4rdSHL/findomain#71]
Hello this is not an issue, is a question. i mass scan a lot of domains to find and save their subdomains and after a couple of scans i start to get banned from the apis and the results start to get lower and lower so my question is:

How much time should i throttle this tool in a bash script in order to not get banned from the apis findomain uses. Does anyone know? i don't know if it would be ok with 30 minutes or 8 hours and honestly it is really hard to test this and needs a lot of time so if anyone knows this and tell me i would appreciate it :)

**Comment by Edu4rdSHL** [comment]
CC @zerodot1

**Comment by ZeroDot1** [comment]
Hi @Edu4rdSHL @marcelo321,

I recommend waiting at least 8-12 hours between scans.
And I recommend to scan a maximum of 500 URLs with one scan run.
If you follow these tips the banning should not be a problem anymore.

**Comment by marcelo321** [comment]
i am now scanning less than 250 domains consecutively and i am getting banned i think.- i repeat the whole scan of those 250 urls every 1 day or more so i respect the 8-12 hours you said.

I just added a `sleep 15m` every 5th scan so i throttle it a bit...

not so long ago i run the same scan to the same target (a big domain with like 100k subdomains) 10 consecutive times, and towards the end some apis started failing and got less results so i would be impressive if i could make 500 consecutive scans without getting banned.

**Comment by Edu4rdSHL** [comment]
Please see #75.
