### ISSUE TITLE
New Passive Source: Subject Alternate Name(SAN)

### ISSUE THREAD

**Issue by xyele** [Edu4rdSHL/findomain#73]
https://appsecco.com/books/subdomain-enumeration/passive_techniques/san.html

https://raw.githubusercontent.com/appsecco/the-art-of-subdomain-enumeration/master/san_subdomain_enum.py

**Comment by kpcyrd** [comment]
there was a recent change in crt.sh, the api returns both the common name and all names in the SAN extension.

**Comment by xyele** [comment]
oh i did not know that. thanks

**Comment by Edu4rdSHL** [comment]
Yes, as @kpycrd says crtsh already implemented that. 

That's the reason why I have to do it: https://github.com/Edu4rdSHL/findomain/blob/0bdd026f8d8864d6c22b3e2e79075ac6f16ad373/src/sources.rs#L238
