### ISSUE TITLE
Custom resolver in configuration file

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#74]
It should be possible to use custom resolvers in the config file.
It would also be best if it were possible to use DNS over TLS, this would greatly improve security.

**Comment by Edu4rdSHL** [comment]
Hello.

See #19 for custom revolvers. DoT is already supported. What do you mean?

**Comment by ZeroDot1** [comment]
Ah yes, I overlooked it, sorry.
It should be easy to simply set one or more URLs for DNS over TLS in the configuration file.
Example: 
your-id.dns.nextdns.io, https://cloudflare-dns.com/dns-query

**Comment by Edu4rdSHL** [comment]
That isnt possible, DNS are IPs, no URLs. When you specify DoT option findomain automatically picks up Cloudflare resolver.

**Comment by ZeroDot1** [comment]
With CURL you can also specify DOT resolver via a URL Example: 

`curl --doh-url https://cloudflare-dns.com/dns-query` 

I haven't seen how it works exactly, but I think it also works with Rust.

**Comment by ZeroDot1** [comment]
Yeah, you're right, I don't know why, something's a bit weird today, sorry.
I think we can close this.
