### ISSUE TITLE
Facebook access token 400 Bad request 

### ISSUE THREAD

**Issue by doflamingo-lab** [Edu4rdSHL/findomain#77]
Hello 

after i feed findomain facebook acess token using this " findomain_fb_token="token"
the tool  return a message like facebook 
--he Facebook API has failed returning the following HTTP status: 400 Bad Request--

Thanks you

**Comment by Edu4rdSHL** [comment]
Hello, it's caused when you ask to the Facebook's API for a domain that they doesn't have in their database, for example `gmail.dasdsad`. You can you try to search for `spotify.com` (for example) and I'm sure you will not get errors.
