### ISSUE TITLE
Missing target root domain name in list

### ISSUE THREAD

**Issue by sumgr0** [Edu4rdSHL/findomain#78]
When using the -m the dB update/webhook push excludes the target root domain name.

For eg. When running findomain against example.com the dB only shows the subdomains of the subs.example.com and excludes the target root domain example.com from the list.

**Comment by Edu4rdSHL** [comment]
Hey @sumgr0, I have fixed this issue in https://github.com/Edu4rdSHL/findomain/commit/258f61ddf9a0a63d9e324664a936021da9c5dc3e.
