### ISSUE TITLE
Colors for better differentiation of messages in the command line. 

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#81]
I recommend to color the output e.g. to highlight errors better.

Error = red or orange
Everything OK e.g. if subdomains are found = light green
Other messages = light blue

**Comment by Edu4rdSHL** [comment]
Hello, thanks for suggesting, I have already looked into it and will be added. No ETA at the moment but will be added.

**Comment by ZeroDot1** [comment]
That sounds very good, thank you very much.

**Comment by Edu4rdSHL** [comment]
This have been implemented.

**Comment by ZeroDot1** [comment]
Thanks for implementing it.
