### ISSUE TITLE
Add support for riddler.io

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#84]
Via riddler.io you can find many subdomains.
curl --tcp-fastopen --tcp-nodelay --compressed -u USER:PASS https://riddler.io/search/exportcsv?q=pld:google.com

https://riddler.io/help/api

Addition:
Username and password should be configurable in the configuration file.

**Comment by Edu4rdSHL** [comment]
Hello, thanks. I was about to close it because in your example there is not a proper API returning a JSON file but seems that adding `output=json` in the JSON post data of the request it will output to JSON.

**Comment by ZeroDot1** [comment]
Thanks, I have used riddler.io a lot in the past, I just had only the CSV example available sorry.

**Comment by kpcyrd** [comment]
It seems they are going to shut down soon according to: https://riddler.io/auth/login

**Comment by Edu4rdSHL** [comment]
Thanks, @kpcyrd. @ZeroDot1 can you investigate if [F-Secure Radar](https://www.f-secure.com/radar) offers something similar?

**Comment by ZeroDot1** [comment]
I'll check it out as soon as possible.

**Comment by ZeroDot1** [comment]
It looks like it is not so easy to get subdomains via radar.
https://help.f-secure.com/data/pdf/radar-3.0-userguide-eng.pdf

**Comment by Edu4rdSHL** [comment]
Thank you for the research!
