### ISSUE TITLE
Add Support for: ctsearch.entrust.com

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#85]
https://ctsearch.entrust.com/api/v1/certificates?fields=subjectDN&domain=google.com&includeExpired=true&exactMatch=false&limit=5000

Found via: https://raw.githubusercontent.com/chris408/ct-exposer/master/ct-exposer.py 

Via ctsearch.entrust.com you can find many subdomains.

**Comment by Edu4rdSHL** [comment]
Hey mate, thanks. Will be added =)

**Comment by ZeroDot1** [comment]
Very good, thank you very much.

**Comment by Edu4rdSHL** [comment]
Added in plus version.
