### ISSUE TITLE
Add support for: web.archive.org

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#86]
https://github.com/Edu4rdSHL/findomain/issues/7#issuecomment-552117819 

Here is an example with CURL:
`curl --tcp-fastopen --tcp-nodelay --silent --compressed "http://web.archive.org/cdx/search/cdx?url=*.coinmine.pl/*&output=text&fl=original&collapse=urlkey" | sed -e 's_https*://__' -e "s/\/.*//" -e 's/:.*//' -e 's/^www\.//' | sed "/@/d" | sed -e 's/\.$//' | sort -u`

**Comment by Edu4rdSHL** [comment]
Duplicated of #44

**Comment by ZeroDot1** [comment]
hmm, okay, I overlooked it, sorry.

**Comment by ZeroDot1** [comment]
If possible, you should add it sometime in the future.
archive.org lists a lot of domains/subdomains that are not found in many other sources.
