### ISSUE TITLE
Allow flag to update DB when webhook faces a timeout error

### ISSUE THREAD

**Issue by sumgr0** [Edu4rdSHL/findomain#87]
Hi!

Currently, when using the -monitoring flag to update the subdomains to the dB, it requires a mandatory webhook to work. However, often times (as personally experienced) when the webhook timeout occurs, the data collected is not updated to the database. 

I understand, this as a failsafe method to allow notification of new subdomains, however, it'll be a good option to bypass the notification (during webhook timeout) to atleast update the db with collected subdomains.

Thanks

**Comment by Edu4rdSHL** [comment]
Hey man, will be implemented really soon.

**Comment by Edu4rdSHL** [comment]
Solved, it will roll out to free version as well, I think.
