### ISSUE TITLE
Compiling error after git pull - unresolved import core::task::Context E0432, E0658

### ISSUE THREAD

**Issue by xtrmbuster** [Edu4rdSHL/findomain#90]
root@toto:~/tools/findomain# cargo build --release
    Updating crates.io index
  Downloaded serde_derive v1.0.105
  Downloaded reqwest v0.10.4
  Downloaded postgres v0.17.2
  Downloaded serde v1.0.105
  Downloaded trust-dns-resolver v0.19.3
  Downloaded futures-core v0.3.4
  Downloaded failure v0.1.7
  Downloaded hyper v0.13.4
  Downloaded pin-project-lite v0.1.4
  Downloaded smallvec v1.2.0
  Downloaded futures-util v0.3.4
  Downloaded backtrace v0.3.44
  Downloaded thiserror v1.0.11
  Downloaded webpki-roots v0.19.0
  Downloaded futures v0.3.4
  Downloaded failure_derive v0.1.7
  Downloaded h2 v0.2.2
  Downloaded futures-channel v0.3.4
  Downloaded trust-dns-rustls v0.19.3
  Downloaded futures-sink v0.3.4
  Downloaded tokio-postgres v0.5.3
  Downloaded futures-io v0.3.4
  Downloaded futures-task v0.3.4
  Downloaded futures-executor v0.3.4
  Downloaded futures-macro v0.3.4
  Downloaded async-trait v0.1.24
  Downloaded thiserror-impl v1.0.11
  Downloaded trust-dns-proto v0.19.3
  Downloaded tokio-util v0.3.1
  Downloaded postgres-types v0.1.1
   Compiling proc-macro2 v1.0.8
   Compiling libc v0.2.66
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.13
   Compiling log v0.4.8
   Compiling semver-parser v0.7.0
   Compiling getrandom v0.1.14
   Compiling typenum v1.11.2
   Compiling cfg-if v0.1.10
   Compiling cc v1.0.50
   Compiling slab v0.4.2
   Compiling autocfg v1.0.0
   Compiling proc-macro-nested v0.1.3
   Compiling pkg-config v0.3.17
   Compiling byteorder v1.3.2
   Compiling memchr v2.3.0
   Compiling futures-core v0.3.4
   Compiling autocfg v0.1.7
error[E0432]: unresolved import `core::task::Context`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:5:18
  |
5 | use core::task::{Context, Poll};
  |                  ^^^^^^^ no `Context` in `task`

error[E0432]: unresolved import `core::task::Context`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:5:18
  |
5 | use core::task::{Context, Poll};
  |                  ^^^^^^^ no `Context` in `task`

error[E0432]: unresolved import `core::task::Context`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/mod.rs:9:22
  |
9 | pub use core::task::{Context, Poll, Waker, RawWaker, RawWakerVTable};
  |                      ^^^^^^^ no `Context` in `task`

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/lib.rs:20:1
   |
20 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/lib.rs:23:39
   |
23 | #[doc(hidden)] pub use self::future::{Future, FusedFuture, TryFuture};
   |                                       ^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:5:27
  |
5 | use core::task::{Context, Poll};
  |                           ^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:7:9
  |
7 | pub use core::future::Future;
  |         ^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:12:55
   |
12 | pub type BoxFuture<'a, T> = Pin<alloc::boxed::Box<dyn Future<Output = T> + Send + 'a>>;
   |                                                       ^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:16:60
   |
16 | pub type LocalBoxFuture<'a, T> = Pin<alloc::boxed::Box<dyn Future<Output = T> + 'a>>;
   |                                                            ^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:26:24
   |
26 | pub trait FusedFuture: Future {
   |                        ^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:57:22
   |
57 | pub trait TryFuture: Future + private_try_future::Sealed {
   |                      ^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:76:23
   |
76 |     where F: ?Sized + Future<Output = Result<T, E>>
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:72:10
   |
72 |     ) -> Poll<Result<Self::Ok, Self::Error>>;
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:82:64
   |
82 |     fn try_poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<F::Output> {
   |                                                                ^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:48:9
   |
48 |     use super::Future;
   |         ^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:52:50
   |
52 |     impl<F, T, E> Sealed for F where F: ?Sized + Future<Output = Result<T, E>> {}
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:5:27
  |
5 | use core::task::{Context, Poll};
  |                           ^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:61:10
   |
61 |     ) -> Poll<Option<Self::Item>>;
   |          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:181:12
    |
181 |         -> Poll<Option<Result<Self::Ok, Self::Error>>>;
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:101:10
    |
101 |     ) -> Poll<Option<Self::Item>> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:120:10
    |
120 |     ) -> Poll<Option<Self::Item>> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:191:12
    |
191 |         -> Poll<Option<Result<Self::Ok, Self::Error>>>
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:208:14
    |
208 |         ) -> Poll<Option<Self::Item>> {
    |              ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/stream.rs:224:14
    |
224 |         ) -> Poll<Option<S::Item>> {
    |              ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/mod.rs:9:31
  |
9 | pub use core::task::{Context, Poll, Waker, RawWaker, RawWakerVTable};
  |                               ^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/mod.rs:9:37
  |
9 | pub use core::task::{Context, Poll, Waker, RawWaker, RawWakerVTable};
  |                                     ^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/mod.rs:9:44
  |
9 | pub use core::task::{Context, Poll, Waker, RawWaker, RawWakerVTable};
  |                                            ^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/mod.rs:9:54
  |
9 | pub use core::task::{Context, Poll, Waker, RawWaker, RawWakerVTable};
  |                                                      ^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/__internal/atomic_waker.rs:5:5
  |
5 | use core::task::Waker;
  |     ^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/__internal/atomic_waker.rs:91:30
   |
91 |     waker: UnsafeCell<Option<Waker>>,
   |                              ^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/__internal/atomic_waker.rs:203:29
    |
203 |         impl AssertSync for Waker {}
    |                             ^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/__internal/atomic_waker.rs:261:36
    |
261 |     pub fn register(&self, waker: &Waker) {
    |                                    ^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/task/__internal/atomic_waker.rs:367:34
    |
367 |     pub fn take(&self) -> Option<Waker> {
    |                                  ^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:12:62
   |
12 | pub type BoxFuture<'a, T> = Pin<alloc::boxed::Box<dyn Future<Output = T> + Send + 'a>>;
   |                                                              ^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:16:67
   |
16 | pub type LocalBoxFuture<'a, T> = Pin<alloc::boxed::Box<dyn Future<Output = T> + 'a>>;
   |                                                                   ^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:76:30
   |
76 |     where F: ?Sized + Future<Output = Result<T, E>>
   |                              ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:82:69
   |
82 |     fn try_poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<F::Output> {
   |                                                                     ^^^^^^^^^

error[E0658]: use of unstable library feature 'futures_api': futures in libcore are unstable (see issue #50547)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.4/src/future.rs:52:57
   |
52 |     impl<F, T, E> Sealed for F where F: ?Sized + Future<Output = Result<T, E>> {}
   |                                                         ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 38 previous errors

Some errors occurred: E0432, E0658.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `futures-core`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Edu4rdSHL** [comment]
What is the output for `cargo -V`?

**Comment by xtrmbuster** [comment]
Ok I saw that you recommend >1.39 i'm going to try
