### ISSUE TITLE
silent option

### ISSUE THREAD

**Issue by atikrahman1** [Edu4rdSHL/findomain#93]
Thanks for the free version of the tool. I would like to see the --silent option which could only output the domain name. Which is better for users to further processing the text file.

thanks

**Comment by Edu4rdSHL** [comment]
Hello, there's `-q/--quiet` which is the equivalent.

**Comment by atikrahman1** [comment]
Hi,

I didn't found any `-q/--quite` option for windows version 
![image](https://user-images.githubusercontent.com/25384315/79189932-cf5bd780-7e44-11ea-895d-e5f99ae01d3d.png)

**Comment by Edu4rdSHL** [comment]
Use the latest version.

**Comment by atikrahman1** [comment]
I am using `findomain 0.2.91` isn't it the latest version? I just download it from your repo yesterday.

**Comment by Edu4rdSHL** [comment]
It is not, latest version is 1.5.0. Please read [the documentation](https://github.com/edu4rdshl/findomain#installation).
